# Generated by Django 2.2 on 2020-03-17 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoronaCounrty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(blank=True, max_length=250, null=True)),
                ('total_cases', models.CharField(blank=True, max_length=250, null=True)),
                ('new_cases', models.CharField(blank=True, max_length=250, null=True)),
                ('total_deaths', models.CharField(blank=True, max_length=250, null=True)),
                ('new_deaths', models.CharField(blank=True, max_length=250, null=True)),
                ('total_recovered', models.CharField(blank=True, max_length=250, null=True)),
                ('active_cases', models.CharField(blank=True, max_length=250, null=True)),
                ('serious_cases', models.CharField(blank=True, max_length=250, null=True)),
                ('tot_cases', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrackCountry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(blank=True, max_length=250, null=True)),
                ('total_cases', models.CharField(blank=True, max_length=250, null=True)),
                ('new_cases', models.CharField(blank=True, max_length=250, null=True)),
                ('total_deaths', models.CharField(blank=True, max_length=250, null=True)),
                ('new_deaths', models.CharField(blank=True, max_length=250, null=True)),
                ('total_recovered', models.CharField(blank=True, max_length=250, null=True)),
                ('active_cases', models.CharField(blank=True, max_length=250, null=True)),
                ('serious_cases', models.CharField(blank=True, max_length=250, null=True)),
                ('tot_cases', models.CharField(blank=True, max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
